"""init schema

Revision ID: e78509347f60
Revises: 
Create Date: 2026-09-30 19:18:09.493775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78509347f60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('staff_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lesson_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('lesson_type', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('effort_note', sa.Text(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('project_stage', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('homework_def', sa.Text(), nullable=False),
    sa.Column('deps', sa.Text(), nullable=False),
    sa.Column('part_group', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('lesson_card', schema=None) as batch_op:
        batch_op.create_index('idx_lesson_module', ['module_id', 'sort_order'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','active','suspended','graduated')", name='ck_student_status'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('idx_student_cohort', ['cohort_id'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_card_id', sa.Integer(), nullable=False),
    sa.Column('act_type', sa.Text(), nullable=False),
    sa.Column('acted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_card_id'], ['lesson_card.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_card_id', 'act_type', name='uq_activity')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.Text(), nullable=False),
    sa.Column('mail_type', sa.Text(), nullable=False),
    sa.Column('lesson_card_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.CheckConstraint("mail_type IN ('verify','reset','welcome','schedule_confirm','schedule_change','preview_reminder','class_reminder')", name='ck_email_log_mail_type'),
    sa.ForeignKeyConstraint(['lesson_card_id'], ['lesson_card.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index('idx_email_dedup', ['student_id', 'mail_type', 'lesson_card_id', 'created_at'], unique=False)

    op.create_table('email_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_card_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('mat_type', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_card_id'], ['lesson_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_card_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['lesson_card_id'], ['lesson_card.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_card_id', name='uq_schedule_student_lesson')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_next', ['student_id', 'status', 'scheduled_at'], unique=False)

    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_next')

    op.drop_table('schedule')
    op.drop_table('material')
    op.drop_table('email_token')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index('idx_email_dedup')

    op.drop_table('email_log')
    op.drop_table('activity')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('idx_student_cohort')

    op.drop_table('student')
    with op.batch_alter_table('lesson_card', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_module')

    op.drop_table('lesson_card')
    op.drop_table('staff_user')
    op.drop_table('module')
    op.drop_table('config')
    op.drop_table('cohort')
    # ### end Alembic commands ###
